name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Pack dist
        run: |
          cd dist
          zip -r ../OneTerminal.zip .

      - name: Публикация файлов
        uses: softprops/action-gh-release@v3
        if: ${{ success() }}
        with:
          prerelease: ${{ inputs.prerelease }}
          files: OneTerminal.zip
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
